# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: CI
on: push
jobs:
  build:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install packages
        run: npm ci
      - name: ESLint
        uses: mrdivyansh/eslint-action@v1.0.7
        with:
          repo-token: ${{secrets.GITHUB_TOKEN}}
          eslint-rc: .eslintrc.json
      - name: Run Jest
        uses: stefanoeb/jest-action@1.0.4
        with:
          jestArgs:  --config jest.config.js
      - name: Npm build
        uses: linchpin/action-build-yarn-npm@master
